services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always

  telegram-bot:
    build:
      context: ./backend
      dockerfile: Dockerfile.bot
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
