services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"  # Optional, if needed by the backend
    networks:
      - app-network
    restart: always

  telegram-bot:
    build:
      context: ./backend
      dockerfile: Dockerfile.bot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
