# backend/Dockerfile.bot
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .env .
COPY .env /app/.env
RUN pip install python-dotenv

COPY . .

CMD ["python", "tgbot.py"]
