# backend/Dockerfile.bot
FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1
ENV LOG_LEVEL=INFO

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install python-dotenv

COPY .env .
COPY . .

CMD ["python", "tgbot.py"]
