name: Deploy to Google Cloud

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCC_SSH_KEY }}

      # Backend and Telegram Bot Deployment
      - name: Deploy backend and bot as Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCC_USER }}@${{ secrets.GCC_SERVER_IP }} << 'EOF'
            cd /path/to/project

            # Pull latest code
            git pull origin main

            # Build and start Docker containers
            docker-compose down  # Stop existing containers
            docker-compose up -d --build  # Build and start new containers
          EOF

      # Frontend Deployment
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install frontend dependencies and build
        working-directory: ./crm
        run: |
          npm install
          npm run build

      - name: Deploy frontend to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCC_USER }}@${{ secrets.GCC_SERVER_IP }} << 'EOF'
            # Copy frontend build files to the server's web directory
            rm -rf /var/www/html/*  # Clear old files
            cp -r crm/build/* /var/www/html/  # Copy new build files
          EOF
